# SA Creation
resource "google_service_account" "service_account" {
  project      = module.init.project_id
  account_id   = "sa-tf-${var.service_account_name}"
  display_name = "Service Account generated by Terraform "
}

resource "google_project_iam_member" "sa_owner_role" {
  project = module.init.project_id
  role    = "roles/owner"
  member  = "serviceAccount:${google_service_account.service_account.email}"
}

resource "google_project_iam_member" "sa_user_role" {
  project = module.init.project_id
  role    = "roles/iam.serviceAccountUser"
  member  = "serviceAccount:${google_service_account.service_account.email}"
}


resource "google_project_iam_member" "compute_metric_writer" {
  project = module.init.project_id
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:${module.init.project_number}-compute@developer.gserviceaccount.com"
}

resource "google_project_iam_member" "compute_log_writer" {
  project = module.init.project_id
  role    = "roles/monitoring.metricWriter"
  member  = "serviceAccount:${module.init.project_number}-compute@developer.gserviceaccount.com"
}